# Generated by Django 2.2 on 2019-12-04 07:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='longitude',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
